version: '3.7'
networks:
  overlay-net:
    external: true      
    driver: overlay
services:
  file-server:
    image: iudx/fs-depl:latest
    volumes:
      - ./secrets/all-verticles-configs/config-depl.json:/usr/share/app/secrets/all-verticles-configs/config.json
    expose:
      - "8080"
      - "9000"
    networks: 
      - overlay-net
