version: '3.7'
networks:
  fs-net:
    driver: bridge
services:
  file-server:
    image: iudx/fs-dev:latest
    volumes:
      - ./secrets/all-verticles-configs/config-dev.json:/usr/share/app/secrets/all-verticles-configs/config.json
    ports:
      - "8081:80"
    networks: 
      - fs-net
