version: '3.7'
services:
  file-server:
    env_file:
      - ./.file-server.env
    volumes:
      - type: volume
        source: fs-volume
        target: /usr/share/app/storage
    restart: always
    logging:
       driver: "json-file"
       options:
          max-file: "3"
          max-size: "5m"
    command: bash -c "exec java $$FS_JAVA_OPTS  -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory -jar ./fatjar.jar  --host $$(hostname) -c secrets/all-verticles-configs/config.json"

volumes:
  fs-volume:
    external: true
